[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#F0F0F0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FA8072"

# Color used for almost all text.
textColor = "#2F4F4F"